const langArr = {
    "header-title": {
        "ru": "Разработчик, влюбленный в разработку и создание цифрового продукта",
        "en": "Developer in love with developing and creating digital product",
        "de": "Entwickler, der es liebt, digitale Produkte zu entwickeln und zu erstellen",
        "jp": "デジタル製品の開発・作成が好きな開発者",
        "fr": "Développeur amoureux du développement et de la création de produits numériques",
    },
    "my-name": {
        "ru": "Максим Литвинов",
        "en": "Maxim Litvinov",
        "de": "Maxim Litwinow",
        "jp": "マキシム・リトビノフ",
        "fr": "Maxim Litvinov",
    },
    "memory": {
        "ru": "объем памяти",
        "en": "memory size",
        "ua": "oбсяг пам'яті",
        "jp": "コメントする",
        "fr": "Markdown est supporté",
    },
    "memory-value": {
        "ru": "4 ГБ",
        "en": "4 GB",
        "ua": "4 ГБ",
        "jp": "4 GB",
        "fr": "4 GB",
    },
    "memory-type": {
        "ru": "тип памяти",
        "en": "memory type",
        "ua": "nип пам'яті",
        "jp": "最近の投稿",
        "fr": "Lire plus",
    },
    "cool": {
        "ru": "тип системы охлаждения",
        "en": "сooling system type",
        "ua": "тип системи охолодження",
        "jp": "コメントを送信する",
        "fr": "Propulsé par",
    },
    "cool-value": {
        "ru": "Активная",
        "en": "Active",
        "ua": "sadasd",
        "jp": "コjhkh",
        "fr": "Propufdd",
    },
    "more": {
        "ru": "детально о товаре",
        "en": "more details",
        "ua": "детально про товар",
        "jp": "送信しました",
        "fr": "Entrez votre recherche",
    },
}